{% set name = "hover" %}
{% set version = "0.8.1" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3852ea8ab36f1f4d50f9ab649e2bda3ec2b78ffda8d7a0ba0e3590b5fa2a35fc

build:
  number: 0
  noarch: python
  script: python -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - bokeh >=2.3.3
    - scikit-learn >=0.20.0
    - pytorch >=1.10.0
    - pandas >=1.3.0
    - numpy >=1.14
    - scipy >=1.3.2
    - tqdm >=4.0
    - rich >=11.0.0
    - deprecated >=1.1.0
    - umap-learn >=0.3.10
    - flexmod >=0.1.1

test:
  imports:
    - hover
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://phurwicz.github.io/hover
  license: MIT
  license_file: LICENSE
  summary: Label data at scale. Fun and precision included.
  dev_url: https://github.com/phurwicz/hover

extra:
  recipe-maintainers:
    - phurwicz
    - haochuanwei
